Convert cleanse into a method, to fix error when latest git feincms-cleanse is used:
Error
Traceback (most recent call last):
  File "/Users/francis/env/goway/lib/python2.6/site-packages/django/utils/unittest/case.py", line 333, in run
    testMethod()
  File "/Users/francis/Code/Bright/python/goway/apps/goway/tests/service/trip_finder.py", line 182, in test_intro_and_hero_image_text_escaping
    add_introduction_to_section_page(section_page, introduction)
  File "/Users/francis/Code/Bright/python/goway/apps/goway/tests/service/utils.py", line 98, in add_introduction_to_section_page
    content.save()
  File "/Users/francis/env/goway/lib/python2.6/site-packages/feincms/content/richtext/models.py", line 98, in save
    self.text = self.cleanse(self.text)
  File "/Users/francis/Code/Bright/python/feincms-cleanse/feincms_cleanse/__init__.py", line 64, in cleanse_html
    allow_tags=allowed_tags.keys() + ['style'],
AttributeError: 'str' object has no attribute 'keys'

The error is caused by the parameters (self, html) being passed to the cleanse function. cleanse_html (from feincms-cleanse 3f771e19) has (html, allowed_tags=cleanse_html_allowed) as its first 2 parameters, so passing (self, html) to it causes html to be a RichTextContent instance and allowed_tags to be the html string during cleanse_html execution, which is obvioysly not what it expects! It ends up raising an AttributeError when it tries to find the keys of allowed_tags, which doesn't work because allowed_tags is erroneously an HTML string.